### ISSUE TITLE
Import Members Not Creating a Order

### ISSUE THREAD

**Issue by laurentruckers** [strangerstudios/pmpro-import-users-from-csv#55]
Since the new update when we import members there is not an order created.

**Comment by andrewlimaza** [comment]
There have been changes when to create the order and it requires certain information to create the order. We only create orders for imports that have a subscription ID this is due to Paid Memberships Pro 3.0 update releasing soon - https://github.com/strangerstudios/pmpro-import-users-from-csv/blob/6eb061cfb871ef917c68fd82521b8254a91f48a0/includes/pmpro-membership-data.php#L223

We have plans to document this on our site in a better way.

**Comment by andrewlimaza** [comment]
I am going to close this issue as orders are being created in these certain cases. You may need to add the required fields to create the order now.
