### ISSUE TITLE
Is it usual that the script taking more than 2 minutes to upload single feild?

### ISSUE THREAD

**Issue by razcakappa** [strangerstudios/pmpro-import-users-from-csv#8]
To add a csv row, it takes more than 2 minutes averagely. Is this normal? Went through the import script however can't find any bottle neck. Anyone got the same issues?

**Comment by ideadude** [comment]
That sounds a little long, but depending on what happens when a user is created and/or changes membership level (e.g. if you have a lot of plugins that are hooked into user_register and/or pmpro_change_membership_level) then it's possible for the import to take a long time.

I'm going to close this issue because it's old (we even had a performance update last year). But please feel free to open the issue again if you are still experience long time outs.
